/*
 * Scala.js (https://www.scala-js.org/)
 *
 * Copyright EPFL.
 *
 * Licensed under Apache License 2.0
 * (https://www.apache.org/licenses/LICENSE-2.0).
 *
 * See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 */

package org.scalajs.linker.interface

import Fingerprint.FingerprintBuilder

/** Output patterns configure how the linker names/refers to modules it created.
 *
 *  Internally, the linker refers to every module using an abstract module ID.
 *
 *  For public modules (i.e. modules that can be imported), the module ID is
 *  provided by the user.
 *
 *  For internal modules (i.e. modules used to share code), the module ID is
 *  generated by the linker.
 *
 *  Currently, all `with*` methods expect a [[java.util.Formatter Formatter]]
 *  pattern taking the module ID as sole string (`%s`) argument.
 */
final class OutputPatterns private (
    private[interface] val jsFile: String,
    private[interface] val sourceMapFile: String,
    private[interface] val moduleName: String,
    private[interface] val jsFileURI: String,
    private[interface] val sourceMapURI: String,
    private[interface] val dtsFile: String
) {

  /** Pattern for the JS file name (the file containing the module's code). */
  def withJSFile(jsFile: String): OutputPatterns =
    copy(jsFile = jsFile)

  /** Pattern for the file name of the source map file of the JS file. */
  def withSourceMapFile(sourceMapFile: String): OutputPatterns =
    copy(sourceMapFile = sourceMapFile)

  /** Pattern for the module name (the string used to import a module). */
  def withModuleName(moduleName: String): OutputPatterns =
    copy(moduleName = moduleName)

  /** Pattern for the "file" field in the source map. */
  def withJSFileURI(jsFileURI: String): OutputPatterns =
    copy(jsFileURI = jsFileURI)

  /** Pattern for the source map URI in the JS file. */
  def withSourceMapURI(sourceMapURI: String): OutputPatterns =
    copy(sourceMapURI = sourceMapURI)

  /** Pattern for the TypeScript declaration file name.
   *
   *  Only used when `outputDeclarations` is enabled in the linker config.
   */
  def withDeclarationFile(dtsFile: String): OutputPatterns =
    copy(dtsFile = dtsFile)

  override def toString(): String = {
    s"""OutputPatterns(
       |  jsFile        = $jsFile,
       |  sourceMapFile = $sourceMapFile,
       |  moduleName    = $moduleName,
       |  jsFileURI     = $jsFileURI,
       |  sourceMapURI  = $sourceMapURI,
       |  dtsFile       = $dtsFile,
       |)""".stripMargin
  }

  private def copy(
      jsFile: String = jsFile,
      sourceMapFile: String = sourceMapFile,
      moduleName: String = moduleName,
      jsFileURI: String = jsFileURI,
      sourceMapURI: String = sourceMapURI,
      dtsFile: String = dtsFile): OutputPatterns = {
    new OutputPatterns(jsFile, sourceMapFile, moduleName, jsFileURI, sourceMapURI, dtsFile)
  }
}

object OutputPatterns {

  /** Default [[OutputPatterns]]; equivalent to `fromJSFile("%s.js")`. */
  val Defaults: OutputPatterns = fromJSFile("%s.js")

  /** Creates [[OutputPatterns]] from a JS file pattern.
   *
   *  Other patterns are derived from the JS file pattern as follows:
   *  - `sourceMapFile`: ".map" is appended.
   *  - `moduleName`: "./" is prepended (relative path import).
   *  - `jsFileURI`: relative URI (same as the provided pattern).
   *  - `sourceMapURI`: relative URI (same as `sourceMapFile`).
   *  - `dtsFile`: a trailing ".js" is replaced by ".d.ts" (else ".d.ts" is appended).
   */
  def fromJSFile(jsFile: String): OutputPatterns = {
    new OutputPatterns(
      jsFile = jsFile,
      sourceMapFile = s"$jsFile.map",
      moduleName = s"./$jsFile",
      jsFileURI = jsFile,
      sourceMapURI = s"$jsFile.map",
      dtsFile = deriveDTSFile(jsFile)
    )
  }

  private def deriveDTSFile(jsFile: String): String =
    if (jsFile.endsWith(".js")) jsFile.substring(0, jsFile.length - 3) + ".d.ts"
    else jsFile + ".d.ts"

  private[interface] implicit object OutputPatternsFingerprint extends Fingerprint[OutputPatterns] {

    override def fingerprint(outputPatterns: OutputPatterns): String = {
      new FingerprintBuilder("OutputPatterns")
        .addField("jsFile", outputPatterns.jsFile)
        .addField("sourceMapFile", outputPatterns.sourceMapFile)
        .addField("moduleName", outputPatterns.moduleName)
        .addField("jsFileURI", outputPatterns.jsFileURI)
        .addField("sourceMapURI", outputPatterns.sourceMapURI)
        .addField("dtsFile", outputPatterns.dtsFile)
        .build()
    }
  }
}
