/*
 * Scala.js (https://www.scala-js.org/)
 *
 * Copyright EPFL.
 *
 * Licensed under Apache License 2.0
 * (https://www.apache.org/licenses/LICENSE-2.0).
 *
 * See the NOTICE file distributed with this work for
 * additional information regarding copyright ownership.
 */

package org.scalajs.linker.backend

import scala.collection.mutable

import org.scalajs.ir.Names._
import org.scalajs.ir.Trees._
import org.scalajs.ir.Types._

import org.scalajs.linker.interface.ModuleKind
import org.scalajs.linker.standard.{LinkedClass, LinkedTopLevelExport, ModuleSet}
import org.scalajs.linker.standard.ModuleSet.ModuleID

/** Best-effort generator of TypeScript declaration files (`.d.ts`).
 *
 *  Given a linked [[ModuleSet.Module]], this produces a `.d.ts` describing the
 *  `@JSExport` / `@JSExportTopLevel` surface of that module. The framing matches
 *  the emitted `.js`: named `export`s for module outputs (`ESModule`,
 *  `CommonJSModule`) and ambient `declare`s for the global `NoModule` output.
 *
 *  The export surface as represented in the IR is JS-interop-typed (`any`). The
 *  real Scala types survive on the underlying `MethodDef`s / `FieldDef`s of the
 *  linked classes, so this generator recovers them by matching each exported
 *  member to its underlying typed member by simple name and arity. Where the
 *  match is ambiguous or absent (e.g. overloads, renamed exports), it falls back
 *  to `any`.
 *
 *  A reference to a class that is itself exported (as a JS class or via a
 *  constructor-function export) resolves to that class's export name; if the
 *  class lives in another module, an `import type` is emitted. Everything else
 *  falls back to `any`.
 *
 *  Known limitations of this implementation (all documented in
 *  `TYPESCRIPT_DECLARATIONS.md`):
 *  - Generics are erased in the IR and therefore lost.
 *  - `Long`, `Char`, arrays and non-exported reference types map to `any`.
 */
private[backend] object TypeScriptDeclarations {

  /** A class that is exported (as a JS class or a constructor function), and
   *  therefore referable by name in a `.d.ts`.
   */
  final case class ClassExport(moduleID: ModuleID, exportName: String)

  /** Builds the map from class name to its export, across all modules. Used to
   *  resolve type references (possibly across modules).
   */
  def classRegistry(modules: List[ModuleSet.Module]): Map[ClassName, ClassExport] = {
    val entries = for {
      module <- modules
      tle <- module.topLevelExports
      entry <- classExportOf(module.id, tle)
    } yield entry
    entries.toMap
  }

  private def classExportOf(moduleID: ModuleID,
      tle: LinkedTopLevelExport): Option[(ClassName, ClassExport)] = {
    tle.tree match {
      case TopLevelJSClassExportDef(_, exportName) =>
        Some(tle.owningClass -> ClassExport(moduleID, exportName))
      case TopLevelMethodExportDef(_, methodDef) =>
        // A constructor-function export also exposes a class under a name.
        constructedClass(methodDef.body).map(_ -> ClassExport(moduleID, tle.exportName))
      case _ =>
        None
    }
  }

  /** Renders the `.d.ts` content for a module as a UTF-16 `String`.
   *
   *  The framing depends on `moduleKind` so that it matches the emitted `.js`:
   *  `ESModule` and `CommonJSModule` produce named `export` declarations, while
   *  `NoModule` (which exposes its exports as globals) produces ambient
   *  `declare` declarations in a script (no top-level `import`/`export`).
   */
  def genModule(module: ModuleSet.Module, moduleKind: ModuleKind,
      classRegistry: Map[ClassName, ClassExport],
      importPathFor: ModuleID => String): String = {
    /* Top-level declaration prefix: `export ` for module outputs, `declare ` for
     * the global (NoModule) output.
     */
    val topLevelPrefix = moduleKind match {
      case ModuleKind.NoModule => "declare "
      case _                   => "export "
    }

    val ctx = new Context(
        classesByName = module.classDefs.map(c => c.className -> c).toMap,
        classRegistry = classRegistry,
        currentModuleID = module.id,
        topLevelPrefix = topLevelPrefix,
        imports = mutable.LinkedHashMap.empty
    )

    /* Render the body first: cross-module type references are collected into
     * `ctx.imports` as a side effect, so the imports must be emitted afterwards.
     */
    val body = new StringBuilder
    if (module.topLevelExports.isEmpty) {
      // An `export {}` makes a module output a valid empty ES module. For the
      // global (NoModule) output, an empty script needs nothing.
      if (moduleKind != ModuleKind.NoModule)
        body.append("export {};\n")
    } else {
      for (tle <- module.topLevelExports) {
        genTopLevelExport(body, tle, ctx)
        body.append('\n')
      }
    }

    val out = new StringBuilder
    out.append("// TypeScript declarations generated by Scala.js. Do not edit.\n\n")
    if (ctx.imports.nonEmpty) {
      for ((sourceModuleID, names) <- ctx.imports)
        out.append(s"import type { ${names.mkString(", ")} } from ${jsString(importPathFor(sourceModuleID))};\n")
      out.append('\n')
    }
    out.append(body)
    out.toString
  }

  /** Lookups and state used while rendering a single module. */
  private final class Context(
      val classesByName: Map[ClassName, LinkedClass],
      val classRegistry: Map[ClassName, ClassExport],
      val currentModuleID: ModuleID,
      val topLevelPrefix: String,
      /** Names to import from other modules, discovered while rendering. */
      val imports: mutable.LinkedHashMap[ModuleID, mutable.LinkedHashSet[String]]
  )

  private def genTopLevelExport(out: StringBuilder, tle: LinkedTopLevelExport,
      ctx: Context): Unit = {
    val owningClass = ctx.classesByName.get(tle.owningClass)

    tle.tree match {
      case TopLevelJSClassExportDef(_, exportName) =>
        genClassExport(out, exportName, owningClass, ctx)

      case TopLevelModuleExportDef(_, exportName) =>
        genModuleExport(out, exportName, owningClass, ctx)

      case TopLevelMethodExportDef(_, methodDef) =>
        /* `@JSExportTopLevel` on a plain Scala class is lowered to a top-level
         * *method* export whose forwarder constructs the class (`new C(...)`).
         * Detect that and render it as a TS `class` instead of a function.
         */
        constructedClass(methodDef.body) match {
          case Some(className) =>
            val targetClass = ctx.classesByName.get(className).orElse(owningClass)
            genConstructorClassExport(out, tle.exportName, methodDef, targetClass, ctx)
          case None =>
            genMethodExport(out, exportName = tle.exportName, methodDef, owningClass, ctx)
        }

      case TopLevelFieldExportDef(_, exportName, field) =>
        genFieldExport(out, exportName, field, owningClass, ctx)
    }
  }

  private def genClassExport(out: StringBuilder, exportName: String,
      owningClass: Option[LinkedClass], ctx: Context): Unit = {
    out.append(s"${ctx.topLevelPrefix}class $exportName {\n")

    for (cls <- owningClass) {
      // Constructors (overload signatures).
      val ctors = cls.methods.filter(_.flags.namespace.isConstructor)
      for (ctor <- ctors)
        out.append(s"  constructor(${renderParams(ctor.args, None, ctx)});\n")

      for (line <- genExportedMemberLines(cls, ctx, inClassBody = true))
        out.append(s"  $line\n")
    }

    out.append("}\n")
  }

  private def genModuleExport(out: StringBuilder, exportName: String,
      owningClass: Option[LinkedClass], ctx: Context): Unit = {
    // A module export is a singleton value, rendered as an object type literal.
    val memberLines = owningClass.toList.flatMap(genExportedMemberLines(_, ctx, inClassBody = false))
    if (memberLines.isEmpty) {
      out.append(s"${ctx.topLevelPrefix}const $exportName: {};\n")
    } else {
      out.append(s"${ctx.topLevelPrefix}const $exportName: {\n")
      for (line <- memberLines)
        out.append(s"  $line\n")
      out.append("};\n")
    }
  }

  /** If `tree` (a top-level method export forwarder body) ultimately constructs
   *  a class, returns that class's name. This is how `@JSExportTopLevel` on a
   *  plain Scala class appears in the linked IR.
   */
  private def constructedClass(tree: Tree): Option[ClassName] = tree match {
    case New(className, _, _)           => Some(className)
    case Block(stats) if stats.nonEmpty => constructedClass(stats.last)
    case Labeled(_, _, body)            => constructedClass(body)
    case Return(expr, _)                => constructedClass(expr)
    case _                              => None
  }

  private def genConstructorClassExport(out: StringBuilder, exportName: String,
      methodDef: JSMethodDef, targetClass: Option[LinkedClass], ctx: Context): Unit = {
    out.append(s"${ctx.topLevelPrefix}class $exportName {\n")

    /* Constructor: recover parameter types from the target class's constructor
     * with matching arity; fall back to `any` params by arity.
     */
    val arity = methodDef.args.size
    val ctorParams = targetClass
      .flatMap(_.methods.find(m => m.flags.namespace.isConstructor && m.args.size == arity))
      .map(ctor => renderParams(ctor.args, None, ctx))
      .getOrElse(renderParams(methodDef.args, methodDef.restParam, ctx, forceAny = true))
    out.append(s"  constructor($ctorParams);\n")

    for {
      cls <- targetClass
      line <- genExportedMemberLines(cls, ctx, inClassBody = true)
    } {
      out.append(s"  $line\n")
    }

    out.append("}\n")
  }

  private def genMethodExport(out: StringBuilder, exportName: String,
      methodDef: JSMethodDef, owningClass: Option[LinkedClass], ctx: Context): Unit = {
    /* A top-level method export forwards to a public method of the owning class.
     * For an exported `object`, that underlying method is an instance method; for
     * a class with a static export, it is static. So we match by name and arity
     * regardless of static-ness.
     */
    val matched = owningClass.flatMap(findMatchingMethodByName(_,
        simpleName = exportName, arity = methodDef.args.size))

    matched match {
      case Some(m) =>
        out.append(
            s"${ctx.topLevelPrefix}function $exportName(${renderParams(m.args, None, ctx)}): ${tsType(m.resultType, ctx)};\n")
      case None =>
        out.append(
            s"${ctx.topLevelPrefix}function $exportName(${renderParams(methodDef.args, methodDef.restParam, ctx, forceAny = true)}): any;\n")
    }
  }

  private def genFieldExport(out: StringBuilder, exportName: String,
      field: FieldIdent, owningClass: Option[LinkedClass], ctx: Context): Unit = {
    val tpe = owningClass.flatMap { cls =>
      cls.fields.collectFirst {
        case fd: FieldDef if fd.name.name == field.name => fd.ftpe
      }
    }.getOrElse(AnyType)

    out.append(s"${ctx.topLevelPrefix}let $exportName: ${tsType(tpe, ctx)};\n")
  }

  /** Renders one line per exported instance/static member of `cls`.
   *
   *  `inClassBody` selects the context: a `class { ... }` body, where `static`
   *  members are written with the `static` keyword; or an object type literal
   *  `{ ... }` (a singleton value), where every member is just a property and
   *  `static` is not valid syntax.
   */
  private def genExportedMemberLines(cls: LinkedClass, ctx: Context,
      inClassBody: Boolean): List[String] = {
    cls.exportedMembers.flatMap {
      case m: JSMethodDef =>
        stringName(m.name).map { name =>
          val static = m.flags.namespace.isStatic
          val prefix = if (inClassBody && static) "static " else ""
          findMatchingMethod(cls, name, m.args.size, static) match {
            case Some(underlying) =>
              s"$prefix${propName(name)}(${renderParams(underlying.args, None, ctx)}): ${tsType(underlying.resultType, ctx)};"
            case None =>
              s"$prefix${propName(name)}(${renderParams(m.args, m.restParam, ctx, forceAny = true)}): any;"
          }
        }

      case p: JSPropertyDef =>
        stringName(p.name).map { name =>
          val static = p.flags.namespace.isStatic
          val prefix = if (inClassBody && static) "static " else ""
          val readOnly = if (p.setterArgAndBody.isEmpty) "readonly " else ""
          // Recover the type from a matching 0-arg getter, if any.
          val tpe = findMatchingMethod(cls, name, arity = 0, static)
            .map(_.resultType)
            .getOrElse(AnyType)
          s"$prefix$readOnly${propName(name)}: ${tsType(tpe, ctx)};"
        }
    }
  }

  /** Finds the unique public, non-constructor method of `cls` with the given
   *  simple name, arity and static-ness. Returns `None` if there is no match or
   *  more than one (e.g. overloads).
   */
  private def findMatchingMethod(cls: LinkedClass, simpleName: String, arity: Int,
      static: Boolean): Option[MethodDef] = {
    val candidates = cls.methods.filter { m =>
      val ns = m.flags.namespace
      ns.isStatic == static &&
      !ns.isPrivate &&
      !ns.isConstructor &&
      m.methodName.simpleName.nameString == simpleName &&
      m.args.size == arity
    }
    candidates match {
      case single :: Nil => Some(single)
      case _             => None
    }
  }

  /** Like [[findMatchingMethod]] but ignores whether the method is static. */
  private def findMatchingMethodByName(cls: LinkedClass, simpleName: String,
      arity: Int): Option[MethodDef] = {
    val candidates = cls.methods.filter { m =>
      val ns = m.flags.namespace
      !ns.isPrivate &&
      !ns.isConstructor &&
      m.methodName.simpleName.nameString == simpleName &&
      m.args.size == arity
    }
    candidates match {
      case single :: Nil => Some(single)
      case _             => None
    }
  }

  private def renderParams(args: List[ParamDef], restParam: Option[ParamDef],
      ctx: Context, forceAny: Boolean = false): String = {
    val parts = args.zipWithIndex.map { case (p, i) =>
      val tpe = if (forceAny) "any" else tsType(p.ptpe, ctx)
      s"${paramName(p, i)}: $tpe"
    }
    val restPart = restParam.map(p => s"...${paramName(p, args.size)}: any[]").toList
    (parts ::: restPart).mkString(", ")
  }

  private def paramName(p: ParamDef, index: Int): String = {
    val raw = p.originalName.getOrElse(p.name.name).toString
    if (isValidIdent(raw)) raw else "arg" + index
  }

  /** Extracts the string name of an exported member whose name is a string
   *  literal (computed names are not representable and are skipped).
   */
  private def stringName(name: Tree): Option[String] = name match {
    case StringLiteral(value) => Some(value)
    case _                    => None
  }

  private def tsType(tpe: Type, ctx: Context): String = tpe match {
    case BooleanType                                             => "boolean"
    case ByteType | ShortType | IntType | FloatType | DoubleType => "number"
    case StringType                                             => "string"
    case VoidType                                               => "void"
    case UndefType                                              => "void"
    case NullType                                               => "null"
    case NothingType                                            => "never"
    case AnyType | AnyNotNullType                               => "any"

    // Runtime-boxed types that are not native JS values.
    case LongType => "any"
    case CharType => "any"

    case ClassType(className, nullable, _) =>
      val base = ctx.classRegistry.get(className) match {
        case Some(ClassExport(sourceModuleID, name)) =>
          if (sourceModuleID != ctx.currentModuleID) {
            // Reference to a class in another module: import its type.
            ctx.imports.getOrElseUpdate(sourceModuleID, mutable.LinkedHashSet.empty).add(name)
          }
          name
        case None =>
          "any"
      }
      if (nullable && base != "any") s"$base | null" else base

    case ArrayType(_, _, _) => "any"

    case ClosureType(paramTypes, resultType, nullable) =>
      val f = "(" + paramTypes.zipWithIndex.map { case (p, i) =>
        s"arg$i: ${tsType(p, ctx)}"
      }.mkString(", ") + ") => " + tsType(resultType, ctx)
      if (nullable) s"($f) | null" else f

    case _: RecordType => "any"
  }

  private def propName(name: String): String =
    if (isValidIdent(name)) name else jsString(name)

  /** A double-quoted, escaped TS/JS string literal. */
  private def jsString(s: String): String = {
    val sb = new StringBuilder
    sb.append('"')
    s.foreach {
      case '\\' => sb.append("\\\\")
      case '"'  => sb.append("\\\"")
      case c    => sb.append(c)
    }
    sb.append('"')
    sb.toString
  }

  private def isValidIdent(s: String): Boolean = {
    s.nonEmpty && {
      val c0 = s.charAt(0)
      (Character.isLetter(c0) || c0 == '_' || c0 == '$') &&
      s.forall(c => Character.isLetterOrDigit(c) || c == '_' || c == '$')
    }
  }
}
